export const Auth = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
};

export const ACTIONS = {
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_ERROR: 'FETCH_USERS_ERROR',
  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  SET_LOADING: 'SET_LOADING',
};